version: '3.7'
services:
  server:
    build:
      context: .
      target: 'base'
    command: 'npm run server'
    volumes:
      - /app/node_modules
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
      - HOST=localhost:3000
  client:
    build:
      context: .
      target: 'base'
    command: 'npm run client'
    ports:
      - 8080:8080
    volumes:
      - /app/node_modules
      - ./src:/app/src